package botexecution.commands;

public enum Commands {
    START,
    HELP,
    CREDITS,

    COMMON,
    GAME,
    DND,
    CAMPAIGN_BOARD,
    PLAYER_BOARD,

    MOFU,
    SEARCH,
    ROLL,

    START_A_GAME,
    PAUSE_A_GAME,
    END_A_GAME,
    CREATE_A_CHARACTER,

    CREATE_A_PLAYER,
    HALT_CREATION,
    CREATE_A_CAMPAIGN,
    END_A_CAMPAIGN,

    SHOW_CAMPAIGNS,
    SHOW_CAMPAIGN_GROUP,
    SET_CAMPAIGN,

    SET_CAMPAIGN_NAME,
    SET_PASSWORD,
    SET_MULTICLASS_LIMIT,
    ADD_A_QUEST,
    EDIT_A_QUEST,
    POST_A_QUEST,
    CLOSE_A_QUEST,
    ADD_AN_ITEM,
    SHOW_AN_ITEM,
    SET_AN_ITEM,
    SEE_CURRENT_ITEM,
    EDIT_CURRENT_ITEM,
    DELETE_AN_ITEM,
    GIVE_AN_ITEM,
    TAKE_AN_ITEM,
    BRING_AN_ITEM,
    EQUIP_AN_ITEM,
    TAKE_OFF_AN_ITEM,
    CHANGE_HEALTH,
    CHANGE_DEATH_THROW_COUNTER,
    CHANGE_EXPERIENCE,
    GIVE_INSPIRATION,
    GIVE_A_SECONDARY_JOB,
    SET_A_PRESTIGE_JOB,

    SHOW_PLAYERS,
    SHOW_PLAYER_PROFILE,
    ADD_A_NOTE,
    EDIT_A_NOTE,
    SHOW_NOTES,

    REQUEST_A_ROLL,
    ASK_DM_FOR_A_ROLL,
    SHOW_A_QUEST_BOARD,
    SHOW_A_QUEST,



}
